### ISSUE TITLE
SSL Read failed, The SSL connection was closed : SDK Code -407.

### ISSUE THREAD

**Issue by tljdebrouwer** [aws/aws-iot-device-sdk-cpp#112]
Hello,

With the pubsub sample I am continously getting the following error:
:210 [WebSocket Wrapper] [0x700009ec1000] [WssFrameRecvCallback:L602] : SSL Read failed, The SSL connection was closed : SDK Code -407.

Via the AWS SDK for nodejs I am able to setup a connection, could you provide me some guidance on where to start looking for this issue?

The connection seems to be successfull:
:387 [Network Read] [0x70000c535000] [HandleConnack:L228] : Network Connect Response. Success : SDK Code 0.

Thanks in advance.

**Comment by tljdebrouwer** [comment]
There was an issue with my policies set on AWS!

**Comment by zanbee** [comment]
Hi, I'm facing the same issue with AppSync subscription. Because I'm coding Cocos2dx, I'm wanting to use a CPP lib to subscribe the AppSync topics. 
Firstly, I make a http post request to AppSync to fetch the connection string, topic and the client-id.
Then, I get the host and the query-string from the connection string, use them to connect to the server.
It can pass through WssHandshake and VerifyHandshakeResponse. However, it cannot receive the data because the SSL connection was closed - SDK Code -407.
In the case of AppSync, I can't find out any places in the AWS Console to change the policy. 
Could you please give me some thoughts?
