### ISSUE TITLE
Use the SDK with C++ Builder

### ISSUE THREAD

**Issue by Preemali** [aws/aws-iot-device-sdk-cpp#176]
Hi,

I'm trying to use the sdk in my project in C++ builder (Embarcadero C++ builder 10.3). 
I tried to create a new project in C++ builder and create exactly the same structure of the current SDK directory there. But I got never-ending issues.
Is there any other way to do this? 
Any help/guidance appreciated.
Thank you

**Comment by graebm** [comment]
I'd need to see build logs to know what specific issues you're talking about and give advice.

Since you're just getting started on your project, I'd suggest that you pick up the new [aws-iot-device-sdk-cpp-v2](https://github.com/aws/aws-iot-device-sdk-cpp-v2) instead of this SDK. The V2 SDK is where AWS will be putting its development and support efforts going forward.
