### ISSUE TITLE
AutoReconnect feature doesn't seem to work

### ISSUE THREAD

**Issue by mzanetti** [aws/aws-iot-device-sdk-cpp#41]
having set client->SetAutoReconnectEnabled(true), I cannot see the library ever reconnecting to aws, if for instance the connection drops because ethernet goes down and back up again.

**Comment by shekharhimanshu** [comment]
The way SDK `auto reconnects` is that it sends a PING message to the server every `keep-alive timeout sec / 2` intervals. You set this interval while calling the mqtt client's `Connect` api. If the PING message failed (because the connection dropped abruptly as in your case), the SDK then assumes that a `reconnect` is needed and then only it will try to `connect` again.

Maybe you are not waiting enough for the SDK to detect a disconnect (i.e. send a PING and fail)?
You can also try reducing the `keep-alive timeout sec` to a very low value (caution: this will increase the frequency of PING messages which are counted as regular messages and hence will be reflected in your AWS IoT usage cost).

**Comment by mzanetti** [comment]
I have set the ping timout to 30 seconds atm. if I unplug my ethernet cable and plug it back in, after 30 secs I get the disconnected callback called but no reconnect attempt is being made.

**Comment by shekharhimanshu** [comment]
Thats interesting. When the SDK `attempts reconnect`, it logs a message [here](https://github.com/aws/aws-iot-device-sdk-cpp/blob/master/src/mqtt/Connect.cpp#L464).

You could try switching on the SDK logs (see how to do that [here](https://github.com/aws/aws-iot-device-sdk-cpp/blob/master/samples/PubSub/PubSub.cpp#L271)) and see if thats the case.
Maybe in your case, the SDK attempted reconnect but failed?

**Comment by mzanetti** [comment]
Thank you for the details on the logging. I have enabled this and I actually do see the reconnect attempt now, and it also succeeds... I did try to post something to a topic where my client code is subscribed to in previous attempts and I am quite certain it didn't work, so I reported that bug. However, now I tried again and it seems to work. No idea why it didn't yesterday. Presumably it indeed failed to reconnect for some reason, but I can't tell for sure as I didn't have the logging system enabled. Anyways, closing this issue, as at this point it seems to tun into a duplicate of #21. I am sorry for the noise.
